# Generated by Django 5.0.6 on 2024-06-15 19:32

import smapp.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, upload_to=smapp.models.profile.file_location),
        ),
    ]
