# Generated by Django 5.0.6 on 2024-06-15 20:21

import smapp.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0003_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.FileField(blank=True, upload_to=smapp.models.profile.file_location),
        ),
    ]
