# Generated by Django 5.0.6 on 2024-06-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0006_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
