# Generated by Django 5.0.6 on 2024-06-16 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0007_alter_profile_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('caption', models.CharField(max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('likers', models.ManyToManyField(blank=True, related_name='likes', to='smapp.profile')),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.CharField(max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.profile')),
                ('rel_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smapp.post')),
            ],
        ),
    ]
